### PR TITLE
Support replica sets in connection url

### PR DESCRIPTION
**Pull request by hviana**

### CODE REVIEW

**Comment by hviana** [comment]
Finished, no more commits. You can Merge If you want.

**Comment by hviana** [comment]
Now I believe that I have finished my contributions.

**Comment by hviana** [comment]
Finished, no more commits. You can Merge If you want. Now I believe that I have finished my contributions.

**Comment by hviana** [comment]
sorry, but I recommend you do a new release (again lol), because I need the resource, and there are also people reporting bugs in relation to this.

**Comment by hviana** [comment]
works just like the node js: mongodb://[username:password@]host1[:port1][,...hostN[:portN]]][/[database][?options]]

**Comment by hviana** [comment]
for full replica set support, it is still necessary to implement the equivalent of the js node "ReplSetManager".

**Comment by marcodali** [comment]
what about mongodb+srv

**Pull request merged**
