### PR TITLE
chore: Run `deno lint` in CI

### PR DESCRIPTION
**Pull request by wafuwafu13**

### CODE REVIEW

**Review by erfanium — APPROVED** [review]

**Comment by manyuanrong** [comment]
Is it possible to ignore the entire bson.d.ts? Because we should not modify this one, it is provided from outside

**Comment by erfanium** [comment]
> Is it possible to ignore the entire bson.d.ts? Because we should not modify this one, it is provided from outside

Yea

**Comment by erfanium** [comment]
Oops, sorry :)

**Comment by wafuwafu13** [comment]
@manyuanrong
> it is provided from outside

I didn't know 💦  
Fixed https://github.com/denodrivers/deno_mongo/pull/298/commits/9ae2063255c62588acf092159cfd2ba26a72f50f

**Pull request merged**
