### PR TITLE
chore(test/03_curd): Improve readability

### PR DESCRIPTION
**Pull request by wafuwafu13**
Figure out what `mongo_test_users` collection save after each tests.

### CODE REVIEW

**Comment by erfanium** [comment]
@wafuwafu13 Thanks for this change. it's sounds like good to me, but we need a major change for tests. i don't know what type of tests are good for our, maybe every test should have initialization, test and clean-up steps and tests should not depend on each other.

Do you have any idea idea this?

**Comment by wafuwafu13** [comment]
@erfanium 

We don't run tests individually (All tests use `testWithClient` and runs in [test/tests.ts](https://github.com/denodrivers/deno_mongo/blob/530ef7da5ff168b3c97ce242bc22b6271e42c2f3/tests/test.ts#L14)).
But If the tests depend on each other, it will be inconvenient. (For example, when updating a test)
So I agree with "every test should have initialization, test and clean-up steps and tests should not depend on each other."

But even if we eliminate the dependency, we are still left with the problem that as long as we run it in [test/tests.ts](https://github.com/denodrivers/deno_mongo/blob/530ef7da5ff168b3c97ce242bc22b6271e42c2f3/tests/test.ts#L14), we cannot run test separately.

So I think it's good to eliminate the dependency, but I don't know if it's good to keep using `testWithClient` and `test/tests.ts`

**Comment by manyuanrong** [comment]
Thank you for your work. But I have some confusion. If the test results are described in the comments, there will be additional and inconvenient maintenance work when modifying the test. I considered that each test does not depend on each other, but there will be a lot of repetitions. When testing the delete operation, the add and search also passed the happypath

**Comment by erfanium** [comment]
> I considered that each test does not depend on each other, but there will be a lot of repetitions.

That's not really a problem if it takes some times to run all the tests, because it still takes less time than fixing these tests when you change something.

It also allows us to run only one specific test and save more time.

**Comment by wafuwafu13** [comment]
>If the test results are described in the comments, there will be additional and inconvenient maintenance work when modifying the test.

I agree so close this PR.

May I create a PR to write tests that do not depend on each other?

**Comment by manyuanrong** [comment]
> May I create other PR to write tests that do not depend on each other?

@wafuwafu13 Of course, welcome to do that

**Pull request closed without merging**
