### PR TITLE
add helper method `dropDatabase`

### PR DESCRIPTION
**Pull request by Jaysok**

### CODE REVIEW

**Comment by erfanium** [comment]
I see CI is failing for a strange reason. but I don'k think there's something wrong with your code

**Comment by erfanium** [comment]
CI it's now okay, you can reopen this PR

**Comment by Jaysok** [comment]
Oh thanks, just after PR I found CI is failing. 

I don't have enough time to review the code at that time, so I simply closed it. 

thanks anyway. :)

**Review by lucsoft — APPROVED** [review]
Looks good to me. Even some Tests!

**Review by erfanium — APPROVED** [review]
Thank you

**Pull request merged**
