### PR TITLE
url parser ok, scram almost complete scram

### PR DESCRIPTION
**Pull request by hviana**
Please, help me to finish SCRAM.

### CODE REVIEW

**Comment by manyuanrong** [comment]
The work seems to be going very well. But I have a question. Why should the algorithm be copied to utils instead of importing remote dependencies?

**Comment by hviana** [comment]
I don't like outbuildings that are not hosted on oficial Deno land. In my opinion too, For a driver, I find it interesting not to have many non std dependencies, it avoids breaking the API. I did the reverse engineering of the driver in Node, and where it is giving authentication error in Deno driver, the message document passed to "commandSingle" seems to be exactly the same message sent by the Driver in Node, so I can't find the reason why the Deno driver is in trouble.

**Comment by manyuanrong** [comment]
The hash algorithm used should be found in deno std, we should use it. And some lints on ci need to be fixed.

**Comment by hviana** [comment]
Ok. Later today i Will make such changes.

**Comment by hviana** [comment]
I think it's ok for the merge. I'm waiting.

**Comment by hviana** [comment]
Hello my dear, I finished the implementation. The scram is working for sha1 and sha256. Now I am also using only the std libs. Only added the saslprep lib in utils, because it does not have an url to import. Of course, many other improvements have been implemented to make such an implementation possible, such as improving the url parser.
Enjoy !, needing just call. I believe that the next features to be implemented would be the api for the gridfs file system and the Change streams.

**Comment by manyuanrong** [comment]
Also need to write tests for authorization

**Comment by hviana** [comment]
you need a database with username and password needed for connection

**Comment by manyuanrong** [comment]
db.addUser function is already available
https://github.com/denodrivers/deno_mongo/blob/refactor/tests/auth.test.ts

**Comment by hviana** [comment]
Tests ok

**Comment by hviana** [comment]
The tests are complete.

**Comment by manyuanrong** [comment]
Do you need to sort out the commit, or I will merge after squash

**Comment by hviana** [comment]
Sorry, I don't know what that means. I really need this feature, if you can merge it.

**Comment by hviana** [comment]
I have no more commiits, I finished my part

**Pull request merged**
