### PR TITLE
Added test for worker thread importing deno_mongo.

### PR DESCRIPTION
**Pull request by carlosaviles**

### CODE REVIEW

**Comment by manyuanrong** [comment]
I don't know if deno test can support running all test cases in the worker?
If it is not supported, perhaps we have to collect the test cases for execution through the fake test method before the worker. Does anyone else understand this? @erfanium @lucacasonato

**Comment by carlosaviles** [comment]
AFAIK, deno test does not offer any worker thread option for testing. For this one test I used the promise-resolve approach which is what they use for testing workers at the deno project itself.

I think another way of approaching it would be to extract the actual test methods (including assertions) to separate modules and then import them in separate worker and non worker tests. Worker tests need to be "awaited" using the adhoc promise-resolve construct and this has to be inside the Deno.test it self.

Or we could pass env variables to the test to decide whether or not to treat it as a worker.

It is the first time I contribute to an open source project, so my apologies for clumsiness and mistakes.

**Comment by erfanium** [comment]
@manyuanrong 
I'm not familiar with workers in Deno, but @carlosaviles's solution seems simple and good to me.

**Comment by manyuanrong** [comment]
testWithClient itself should be a good point to add some logic so that they can be tested in the worker. Just to provide such ideas, let's merge first. 
need to resolve the conflict

**Comment by erfanium** [comment]
@manyuanrong I fixed the conflict problem, I'll merge it because you approved it before

**Pull request merged**
